// Canonical ATLAS-01 seed data — the floor stack from PRD §7.2, plus a starter
// incident feed and broadcast. This module has NO database dependency so it can
// be imported by both the API layer (seed fallback) and the seed script.

import type {
  Broadcast,
  Building,
  BuildingCompliance,
  Floor,
  Incident,
  SensorPoint,
} from "@/lib/types";

/** ATLAS-01 floor stack, ordered bottom → top by physical level. */
export const seedFloors: Floor[] = [
  {
    key: "reclamation-core",
    name: "Reclamation Core",
    need: "water",
    category: "Water & Waste",
    level: -1,
    residents: 0,
    metrics: { waterLph: 1840, waterReusePct: 92, energyKw: 12, tempC: 18 },
    occupancyGroup: "F",
    useScope: "mechanical",
    regulatoryNotes: [
      "Non-potable reuse only (CSA B128)",
      "MECP ECA required",
      "Bulk reservoir relocated here",
    ],
  },
  {
    key: "commons-clinic",
    name: "Commons & Clinic",
    need: "health",
    category: "Community & Health",
    level: 1,
    residents: 0,
    metrics: { occupancy: 34, tempC: 21.5, humidityPct: 44, co2Ppm: 620 },
    occupancyGroup: "D",
    useScope: "business",
    regulatoryNotes: [
      "Telehealth + first-aid (avoids Group B care occupancy)",
    ],
  },
  {
    key: "power-ops-core",
    name: "Power & Ops Core",
    need: "energy",
    category: "Energy & Intelligence",
    level: 2,
    residents: 0,
    metrics: { energyKw: 148, loadKw: 96, batteryPct: 78 },
    occupancyGroup: "F",
    useScope: "mechanical",
    regulatoryNotes: [
      "Grid-tied + islanding",
      "ESS to energy-storage fire code",
    ],
  },
  {
    key: "aquaponics-bay",
    name: "Aquaponics Bay",
    need: "food",
    category: "Protein (Food)",
    level: 3,
    residents: 0,
    metrics: { foodKgDay: 41, waterLph: 320, tempC: 23, energyKw: 18 },
    occupancyGroup: "F",
    useScope: "amenity",
    regulatoryNotes: [
      "Closed-loop amenity food — no external sale",
      "Wet-location electrical",
    ],
  },
  {
    key: "vertical-farm",
    name: "Vertical Farm",
    need: "food",
    category: "Produce (Food)",
    level: 4,
    residents: 0,
    metrics: { foodKgDay: 86, energyKw: 54, humidityPct: 65, tempC: 22 },
    occupancyGroup: "F",
    useScope: "amenity",
    regulatoryNotes: [
      "Amenity produce — no commercial sale",
      "Humidity-separated from residences",
    ],
  },
  {
    key: "residences-a",
    name: "Residences A",
    need: "shelter",
    category: "Shelter",
    level: 5,
    residents: 28,
    metrics: { occupancy: 24, loadKw: 22, tempC: 21, humidityPct: 41 },
    occupancyGroup: "C",
    useScope: "residential",
    dwellings: 14,
    beds: 30,
    regulatoryNotes: ["Market multi-unit dwellings"],
  },
  {
    key: "residences-b",
    name: "Residences B",
    need: "shelter",
    category: "Shelter",
    level: 6,
    residents: 28,
    metrics: { occupancy: 21, loadKw: 19, tempC: 21.2, humidityPct: 42 },
    occupancyGroup: "C",
    useScope: "residential",
    dwellings: 14,
    beds: 30,
    regulatoryNotes: ["Market multi-unit dwellings"],
  },
  {
    key: "residences-c",
    name: "Residences C",
    need: "shelter",
    category: "Shelter",
    level: 7,
    residents: 26,
    metrics: { occupancy: 23, loadKw: 20, tempC: 20.8, humidityPct: 40 },
    occupancyGroup: "C",
    useScope: "residential",
    dwellings: 12,
    beds: 28,
    regulatoryNotes: ["Market multi-unit dwellings"],
  },
  {
    key: "residences-d",
    name: "Residences D",
    need: "shelter",
    category: "Shelter",
    level: 8,
    residents: 24,
    metrics: { occupancy: 18, loadKw: 17, tempC: 21.1, humidityPct: 43 },
    occupancyGroup: "C",
    useScope: "residential",
    dwellings: 12,
    beds: 28,
    regulatoryNotes: ["Market multi-unit dwellings"],
  },
  {
    key: "the-lung",
    name: "The Lung",
    need: "air",
    category: "Air & Restoration",
    level: 9,
    residents: 0,
    metrics: { co2Ppm: 410, pm25: 4, humidityPct: 55, occupancy: 9, tempC: 22 },
    occupancyGroup: "F",
    useScope: "mechanical",
    regulatoryNotes: ["Air handling; airtight separation under residences"],
  },
  {
    key: "penthouses",
    name: "The Penthouses",
    need: "shelter",
    category: "Shelter · 12 Penthouses",
    // Up to 12 premium dwellings sharing the rooftop Skydeck pool directly above.
    level: 10,
    residents: 22,
    metrics: { occupancy: 16, loadKw: 24, tempC: 21.4, humidityPct: 42 },
    occupancyGroup: "C",
    useScope: "residential",
    dwellings: 12,
    beds: 24,
    regulatoryNotes: ["Market premium dwellings; Skydeck pool above"],
  },
  {
    key: "skydeck-reservoir",
    name: "Skydeck & Reservoir",
    need: "restoration",
    category: "Restoration / Reserve · Shared rooftop pool",
    level: 11,
    residents: 0,
    metrics: { waterLph: 0, waterReusePct: 100, occupancy: 12, tempC: 24 },
    occupancyGroup: "C",
    useScope: "amenity",
    regulatoryNotes: [
      "Pool only on roof; reservoir relocated to Reclamation Core",
    ],
  },
];

/** Starter incident feed, newest first. */
export const seedIncidents: Incident[] = [
  {
    id: "seed-inc-1",
    severity: "warn",
    floorKey: "vertical-farm",
    title: "Grow-light bank 3 drawing 12% over baseline",
    detail:
      "Photoperiod controller flagged anomalous draw. AI ops proposes shifting the bank to off-peak; awaiting operator approval.",
    createdAt: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
  },
  {
    id: "seed-inc-2",
    severity: "info",
    floorKey: "power-ops-core",
    title: "Battery wall crossed 75% — switching to solar-direct loads",
    detail: "Demand-response routine engaged. Grid import remains at 0 kW.",
    createdAt: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
  },
  {
    id: "seed-inc-3",
    severity: "crit",
    floorKey: "reclamation-core",
    title: "Blackwater pump B fault — failover to pump A confirmed",
    detail:
      "Deterministic controller handled failover locally. No service interruption. Maintenance ticket auto-created.",
    createdAt: new Date(Date.now() - 1000 * 60 * 41).toISOString(),
  },
  {
    id: "seed-inc-4",
    severity: "ok",
    floorKey: "commons-clinic",
    title: "Telehealth link tested green for evening clinic block",
    createdAt: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
  },
];

/** Starter broadcast history. */
export const seedBroadcasts: Broadcast[] = [
  {
    id: "seed-bc-1",
    message:
      "Fresh harvest from the Vertical Farm is available in the Commons kitchen this evening.",
    audience: "all",
    recipients: 106,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
];

// --- F11: sensor ingestion ---
//
// Starter telemetry points across the ATLAS-01 floor stack. Each carries a
// Brick-style dotted `tag` and an equivalent flat Haystack-style `markers`
// list. `ts` is staggered over the last few minutes to look like live ingest.
const sensorTs = (minutesAgo: number) =>
  new Date(Date.now() - 1000 * 60 * minutesAgo).toISOString();

export const seedSensorPoints: SensorPoint[] = [
  // Reclamation Core (water & waste)
  {
    id: "sp-reclamation-core-flow",
    tag: "sensor.water.flow",
    markers: ["sensor", "water", "flow"],
    floorKey: "reclamation-core",
    unit: "main-loop",
    kind: "flow",
    value: 1840,
    unitOfMeasure: "L/h",
    ts: sensorTs(1),
  },
  {
    id: "sp-reclamation-core-reuse",
    tag: "sensor.water.reuse",
    markers: ["sensor", "water", "reuse", "efficiency"],
    floorKey: "reclamation-core",
    kind: "ratio",
    value: 92,
    unitOfMeasure: "%",
    ts: sensorTs(1),
  },
  // Power & Ops Core (energy)
  {
    id: "sp-power-ops-core-power",
    tag: "sensor.electric.power",
    markers: ["sensor", "electric", "power", "gen"],
    floorKey: "power-ops-core",
    unit: "pv-array",
    kind: "power",
    value: 148,
    unitOfMeasure: "kW",
    ts: sensorTs(2),
  },
  {
    id: "sp-power-ops-core-load",
    tag: "sensor.electric.power",
    markers: ["sensor", "electric", "power", "load"],
    floorKey: "power-ops-core",
    unit: "main-bus",
    kind: "power",
    value: 96,
    unitOfMeasure: "kW",
    ts: sensorTs(2),
  },
  {
    id: "sp-power-ops-core-soc",
    tag: "sensor.electric.battery.soc",
    markers: ["sensor", "electric", "battery", "soc"],
    floorKey: "power-ops-core",
    unit: "battery-wall",
    kind: "ratio",
    value: 78,
    unitOfMeasure: "%",
    ts: sensorTs(2),
  },
  // Aquaponics Bay (food)
  {
    id: "sp-aquaponics-bay-temp",
    tag: "sensor.water.temp",
    markers: ["sensor", "water", "temp"],
    floorKey: "aquaponics-bay",
    unit: "fish-tank-1",
    kind: "temp",
    value: 23,
    unitOfMeasure: "°C",
    ts: sensorTs(3),
  },
  {
    id: "sp-aquaponics-bay-flow",
    tag: "sensor.water.flow",
    markers: ["sensor", "water", "flow"],
    floorKey: "aquaponics-bay",
    unit: "grow-bed-loop",
    kind: "flow",
    value: 320,
    unitOfMeasure: "L/h",
    ts: sensorTs(3),
  },
  // Vertical Farm (food)
  {
    id: "sp-vertical-farm-power",
    tag: "sensor.electric.power",
    markers: ["sensor", "electric", "power", "load", "lighting"],
    floorKey: "vertical-farm",
    unit: "grow-light-bank-3",
    kind: "power",
    value: 54,
    unitOfMeasure: "kW",
    ts: sensorTs(4),
  },
  {
    id: "sp-vertical-farm-humidity",
    tag: "sensor.air.humidity",
    markers: ["sensor", "air", "humidity"],
    floorKey: "vertical-farm",
    kind: "humidity",
    value: 65,
    unitOfMeasure: "%",
    ts: sensorTs(4),
  },
  // Residences A (shelter)
  {
    id: "sp-residences-a-temp",
    tag: "sensor.air.temp",
    markers: ["sensor", "air", "temp", "zone"],
    floorKey: "residences-a",
    kind: "temp",
    value: 21,
    unitOfMeasure: "°C",
    ts: sensorTs(5),
  },
  {
    id: "sp-residences-a-occupancy",
    tag: "sensor.occupancy.count",
    markers: ["sensor", "occupancy", "count"],
    floorKey: "residences-a",
    kind: "occupancy",
    value: 24,
    unitOfMeasure: "people",
    ts: sensorTs(5),
  },
  // The Lung (air & restoration)
  {
    id: "sp-the-lung-co2",
    tag: "sensor.air.co2",
    markers: ["sensor", "air", "co2"],
    floorKey: "the-lung",
    kind: "co2",
    value: 410,
    unitOfMeasure: "ppm",
    ts: sensorTs(2),
  },
  {
    id: "sp-the-lung-pm25",
    tag: "sensor.air.pm25",
    markers: ["sensor", "air", "pm25", "particulate"],
    floorKey: "the-lung",
    kind: "pm25",
    value: 4,
    unitOfMeasure: "µg/m³",
    ts: sensorTs(2),
  },
  // Skydeck & Reservoir (restoration)
  {
    id: "sp-skydeck-reservoir-temp",
    tag: "sensor.water.temp",
    markers: ["sensor", "water", "temp", "reservoir"],
    floorKey: "skydeck-reservoir",
    unit: "rooftop-pool",
    kind: "temp",
    value: 24,
    unitOfMeasure: "°C",
    ts: sensorTs(6),
  },

  // RuView WiFi-CSI presence & vital-sign points (github.com/ruvnet/RuView, MIT)
  // Commons & Clinic — presence headcount + vital signs (health floor showcase)
  {
    id: "sp-commons-clinic-presence-count",
    tag: "sensor.presence.count",
    markers: ["sensor", "presence", "count"],
    floorKey: "commons-clinic",
    kind: "presence",
    value: 34,
    unitOfMeasure: "people",
    ts: sensorTs(1),
  },
  {
    id: "sp-commons-clinic-vital-breathing",
    tag: "sensor.vital.breathing",
    markers: ["sensor", "vital", "breathing"],
    floorKey: "commons-clinic",
    kind: "vital",
    value: 14,
    unitOfMeasure: "bpm",
    ts: sensorTs(1),
  },
  {
    id: "sp-commons-clinic-vital-heart",
    tag: "sensor.vital.heart",
    markers: ["sensor", "vital", "heart"],
    floorKey: "commons-clinic",
    kind: "vital",
    value: 68,
    unitOfMeasure: "bpm",
    ts: sensorTs(1),
  },
  // Residences A — presence headcount + occupied confidence
  {
    id: "sp-residences-a-presence-count",
    tag: "sensor.presence.count",
    markers: ["sensor", "presence", "count"],
    floorKey: "residences-a",
    kind: "presence",
    value: 24,
    unitOfMeasure: "people",
    ts: sensorTs(2),
  },
  {
    id: "sp-residences-a-presence-occupied",
    tag: "sensor.presence.occupied",
    markers: ["sensor", "presence", "occupied"],
    floorKey: "residences-a",
    kind: "presence",
    value: 95,
    unitOfMeasure: "%",
    ts: sensorTs(2),
  },
  // The Lung (air & restoration) — presence headcount
  {
    id: "sp-the-lung-presence-count",
    tag: "sensor.presence.count",
    markers: ["sensor", "presence", "count"],
    floorKey: "the-lung",
    kind: "presence",
    value: 9,
    unitOfMeasure: "people",
    ts: sensorTs(2),
  },
];

// --- F7: fleet ---

/**
 * The ATLAS fleet — buildings deployed across Canada and the US. ATLAS-01 is
 * the flagship (online); the rest vary in status to exercise the fleet map.
 * Coordinates are real city lat/lng so the normalized plot reads correctly.
 */
export const seedBuildings: Building[] = [
  {
    id: "atlas-01",
    name: "ATLAS-01 · Toronto",
    location: { label: "Toronto, ON", lat: 43.6532, lng: -79.3832 },
    status: "online",
    // `unitCount` = floors in the stack. `dwellings` = homes (what a lender
    // underwrites); `beds` = sleeping capacity; `residents` = current occupancy.
    // These were deliberately separated — see docs/ATLAS-derisking-plan.md.
    unitCount: 12,
    dwellings: 64,
    beds: 140,
    autonomyPct: 96,
    residents: 128,
    openIncidents: 1,
    gridTied: true,
    islandCapable: true,
    compliance: {
      elevators: 2,
      firefighterElevator: true,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: true,
      dualPlumbing: true,
      mecpEcaStatus: "pre-consultation",
      reservoirLocation: "basement",
      essFireCompliant: true,
    } satisfies BuildingCompliance,
  },
  {
    id: "atlas-02",
    name: "ATLAS-02 · Montréal",
    location: { label: "Montréal, QC", lat: 45.5019, lng: -73.5674 },
    status: "online",
    unitCount: 10,
    dwellings: 52,
    beds: 116,
    autonomyPct: 91,
    residents: 104,
    openIncidents: 0,
    gridTied: true,
    islandCapable: true,
    compliance: {
      elevators: 2,
      firefighterElevator: true,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: true,
      dualPlumbing: true,
      mecpEcaStatus: "in-review",
      reservoirLocation: "basement",
      essFireCompliant: true,
    } satisfies BuildingCompliance,
  },
  {
    id: "atlas-03",
    name: "ATLAS-03 · Vancouver",
    location: { label: "Vancouver, BC", lat: 49.2827, lng: -123.1207 },
    status: "degraded",
    unitCount: 11,
    dwellings: 58,
    beds: 128,
    autonomyPct: 74,
    residents: 116,
    openIncidents: 3,
    gridTied: true,
    islandCapable: true,
    compliance: {
      elevators: 2,
      firefighterElevator: true,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: true,
      dualPlumbing: true,
      mecpEcaStatus: "in-review",
      reservoirLocation: "basement",
      essFireCompliant: true,
    } satisfies BuildingCompliance,
  },
  {
    id: "atlas-04",
    name: "ATLAS-04 · Calgary",
    location: { label: "Calgary, AB", lat: 51.0447, lng: -114.0719 },
    status: "online",
    unitCount: 9,
    dwellings: 46,
    beds: 102,
    autonomyPct: 88,
    residents: 92,
    openIncidents: 1,
    gridTied: true,
    islandCapable: true,
    compliance: {
      elevators: 2,
      firefighterElevator: true,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: true,
      dualPlumbing: true,
      mecpEcaStatus: "approved",
      reservoirLocation: "basement",
      essFireCompliant: true,
    } satisfies BuildingCompliance,
  },
  {
    id: "atlas-05",
    name: "ATLAS-05 · Detroit",
    location: { label: "Detroit, MI", lat: 42.3314, lng: -83.0458 },
    status: "degraded",
    unitCount: 8,
    dwellings: 40,
    beds: 88,
    autonomyPct: 69,
    residents: 78,
    openIncidents: 2,
    gridTied: true,
    islandCapable: true,
    compliance: {
      elevators: 2,
      firefighterElevator: false,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: true,
      dualPlumbing: true,
      mecpEcaStatus: "in-review",
      reservoirLocation: "basement",
      essFireCompliant: true,
    } satisfies BuildingCompliance,
  },
  {
    id: "atlas-06",
    name: "ATLAS-06 · Buffalo",
    location: { label: "Buffalo, NY", lat: 42.8864, lng: -78.8784 },
    status: "offline",
    unitCount: 7,
    dwellings: 34,
    beds: 74,
    autonomyPct: 0,
    residents: 64,
    openIncidents: 5,
    gridTied: true,
    islandCapable: false,
    compliance: {
      elevators: 1,
      firefighterElevator: false,
      exitStairs: 2,
      sprinklered: true,
      barrierFree: false,
      dualPlumbing: false,
      mecpEcaStatus: "not-started",
      reservoirLocation: "roof",
      essFireCompliant: false,
    } satisfies BuildingCompliance,
  },
];
