import type { MetadataRoute } from "next";

// Web App Manifest (served at /manifest.webmanifest). Makes ATLAS OS an
// installable PWA — standalone display, branded icons, dark theme to match the
// console chrome. Icons are generated by scripts/gen-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "ATLAS OS — Habitat Twin",
    short_name: "ATLAS OS",
    description:
      "Building operations platform for self-sufficient ATLAS habitats. Live per-floor telemetry, incident triage, and resident broadcast over an interactive 3D digital twin.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#070b10",
    theme_color: "#070b10",
    categories: ["productivity", "utilities", "business"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
